### ISSUE TITLE
Can we make this work for other sites besides Netflix? 

### ISSUE THREAD

**Issue by aaron13100** [DeeFrancois/netflix-dual-subs#5]
Specifically amazon prime, amazon.co.jp, is what I'm interested in.

thanks

**Comment by DeeFrancois** [comment]
Hey! sorry for the late response. 

Yes it should be possible. It would even work better since Prime Video apparently doesn't use images for certain languages like Netflix does. Which means the "Recommended Method" might actually work for every language.

The next time I'm free (in a couple days maybe) I'll get started on the Prime Video version. Not yet sure if I should add it to this extension or make it its own thing. Regardless, I'll comment here again when I have a working version for you to use.

**Comment by aaron13100** [comment]
Maybe this will be helpful.

```
var target = document.querySelector('.fk87jrb');

// hide the original subtitles.
target.style.opacity = 0;

function getTextContentHolder() {
	// sometimes there's a sub element that holds the subtitle 
	// text and sometimes not.
	var textContentSelector1 = '.atvwebplayersdk-captions-text span';
	var textContentSelector2 = '.atvwebplayersdk-captions-text';

	var textContentHolder = target.querySelector(textContentSelector1);
	if (!textContentHolder) {
		textContentHolder = target.querySelector(textContentSelector2);
	}

	return textContentHolder;
}
// create a mutation observer: https://stackoverflow.com/a/42805882
var observer = new MutationObserver(function(mutations) {
		var textContentHolder = getTextContentHolder();
		if (!textContentHolder) {
			return;
		}
		console.log(target.innerText);
		setFloatingElementText(target.innerText);
});

// Pass in the target node, as well as the observer options.
observer.observe(target, {
    childList: true,
    attributes: true,
    characterData: true,
    subtree: true,
});

function setFloatingElementText(text) {
	var floatingElement = document.querySelector('.runtime-special-div');
	if (!floatingElement) {
		floatingElement = addFloatingElement();
	}
	floatingElement.textContent = text;
	var hm = floatingElement.offsetHeight;
}

function addFloatingElement() {
	var div = document.createElement("div");
	div.style.width = "auto";
	div.style.height = "auto";
	div.style.padding = "1em";
	div.style.background = "rgba(0, 0, 0, 0.75)";
	div.style.color = "white";
	div.style.float = 'left';
	div.style.position = 'fixed';
	div.style.bottom = '5%';
	div.style.left = '1%';
	div.style.display = 'inline-block';
	div.style.zIndex = '99999999';
	div.style.fontSize = '2em';
	div.style.borderRadius = '1em';
	div.classList.add('runtime-special-div');
	div.innerHTML = "こんにちは";
	document.body.appendChild(div);

	return div;
}
```

**Comment by DeeFrancois** [comment]
Sorry, life got in the way.

If you or anyone else reading this actually still cares about this, I do plan on making this extension work for other websites soon, but I don't think I'll actually push those updates to the chrome store for a while. I just can't afford to maintain an extension that works for that many different sites at the moment. So they'll just be available through a separate branch.

My current plan is to start pushing out updates for other sites this weekend. The order will probably be Prime Video, Disney+, Hulu, HBO. I'll see how I feel after working on those and give another update about this then. Maybe it'll be easy enough that maintenance won't seem as tedious as I assume it would be.
